2024-07-12T10:17:28,391 Non-user install because user site-packages disabled
2024-07-12T10:17:28,504 Created temporary directory: /tmp/pip-ephem-wheel-cache-16bqq688
2024-07-12T10:17:28,505 Created temporary directory: /tmp/pip-req-tracker-434oil49
2024-07-12T10:17:28,505 Initialized build tracking at /tmp/pip-req-tracker-434oil49
2024-07-12T10:17:28,505 Created build tracker: /tmp/pip-req-tracker-434oil49
2024-07-12T10:17:28,505 Entered build tracker: /tmp/pip-req-tracker-434oil49
2024-07-12T10:17:28,506 Created temporary directory: /tmp/pip-install-ef42cf_k
2024-07-12T10:17:28,517 1 location(s) to search for versions of pip-reviewpip-review:
2024-07-12T10:17:28,517 * https://pypi.org/simple/pip-reviewpip-review/
2024-07-12T10:17:28,517 Fetching project page and analyzing links: https://pypi.org/simple/pip-reviewpip-review/
2024-07-12T10:17:28,517 Getting page https://pypi.org/simple/pip-reviewpip-review/
2024-07-12T10:17:28,518 Found index url https://pypi.org/simple
2024-07-12T10:17:28,520 Looking up "https://pypi.org/simple/pip-reviewpip-review/" in the cache
2024-07-12T10:17:28,520 Request header has "max_age" as 0, cache bypassed
2024-07-12T10:17:28,522 Starting new HTTPS connection (1): pypi.org:443
2024-07-12T10:17:28,744 https://pypi.org:443 "GET /simple/pip-reviewpip-review/ HTTP/1.1" 404 13
2024-07-12T10:17:28,744 Status code 404 not in (200, 203, 300, 301)
2024-07-12T10:17:28,745 Could not fetch URL https://pypi.org/simple/pip-reviewpip-review/: 404 Client Error: Not Found for url: https://pypi.org/simple/pip-reviewpip-review/ - skipping
2024-07-12T10:17:28,746 Given no hashes to check 0 links for project 'pip-reviewpip-review': discarding no candidates
2024-07-12T10:17:28,746 ERROR: Could not find a version that satisfies the requirement pip-reviewpip-review (from versions: none)
2024-07-12T10:17:28,746 Cleaning up...
2024-07-12T10:17:28,747 Removed build tracker: '/tmp/pip-req-tracker-434oil49'
2024-07-12T10:17:28,747 ERROR: No matching distribution found for pip-reviewpip-review
2024-07-12T10:17:28,747 Exception information:
2024-07-12T10:17:28,747 Traceback (most recent call last):
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
2024-07-12T10:17:28,747     status = self.run(options, args)
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
2024-07-12T10:17:28,747     resolver.resolve(requirement_set)
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
2024-07-12T10:17:28,747     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
2024-07-12T10:17:28,747     abstract_dist = self._get_abstract_dist_for(req_to_install)
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
2024-07-12T10:17:28,747     req.populate_link(self.finder, upgrade_allowed, require_hashes)
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
2024-07-12T10:17:28,747     self.link = finder.find_requirement(self, upgrade)
2024-07-12T10:17:28,747   File "/home/solon/Trybe/projetos/sd-022-b-restaurant-orders/.venv/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
2024-07-12T10:17:28,747     raise DistributionNotFound(
2024-07-12T10:17:28,747 pip._internal.exceptions.DistributionNotFound: No matching distribution found for pip-reviewpip-review
